# config.yaml

llms:
  localllm:
    type: ollama
    model: llama3.2:3b

tools:
  web_search:
    type: web_search
    timeout: 5

  datetime:
    type: datetime

agents:
  datechecker:
    type: simple
    llm: localllm
    tools: [datetime]
    system_prompt: |
      You are a date checker. retrive and establish today's date.
    max_steps: 3
    retry_on_fail: false
    
  researcher:
    type: simple
    llm: localllm
    tools: [web_search]
    system_prompt: |
      You are a research agent. search online and check everything based on today's date
    max_steps: 3
    retry_on_fail: false

  writer:
    type: simple
    llm: localllm
    tools: []
    system_prompt: |
      You are a professional writer. Turn the research content into well-structured prose.
    max_steps: 2

graphs:
  main_flow:
    type: main_flow
